name: zest_trip
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  google_sign_in: ^6.1.5
  equatable: ^2.0.5
  #state
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  firebase_auth: ^4.7.2
  firebase_core: ^2.14.0
  # connectivity_plus: ^4.0.1
  #hooks
  # flutter_hooks: ^0.20.0
  get_it: ^7.6.4
  shared_preferences: ^2.2.0
  flutter_native_splash: ^2.2.19
  jwt_decode: ^0.3.1
  flutter_secure_storage: ^8.0.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  flutter_otp_text_field: ^1.1.1
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  webview_flutter: ^4.4.1
  fluttertoast: ^8.2.4
  google_maps_flutter: ^2.5.0
  # geolocator: ^10.1.0
  # bloc_concurrency: ^0.2.2
  photo_view: ^0.14.0
  readmore: ^2.2.0
  # table_calendar: ^3.0.9
  logger:
    ^2.0.2+1
  mime: ^1.0.4
  flutter_typeahead: ^4.8.0

    #Database

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  built_value_generator: ^8.6.1
  firebase_auth_platform_interface: ^6.15.0
  firebase_core_platform_interface: ^4.8.0

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/logo-green2.png
  image_dark: assets/images/logo-green2.png

  android_12:
    image: assets/images/logo-green2.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/logo-green2.png
    icon_background_color_dark: "#FFFFFF"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launch-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/fonts
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/icons/tags/
    - assets/icons/vehicles/
    - assets/icons/app/
  fonts:
    # - family: AirbnbCereal
    #   fonts:
    #     - asset: assets/fonts/AirbnbCerealBlack/AirbnbCerealBlack.ttf
    #     - asset: assets/fonts/AirbnbCerealBlack/AirbnbCerealBold.ttf
    #     - asset: assets/fonts/AirbnbCerealBlack/AirbnbCerealBook.ttf
    #     - asset: assets/fonts/AirbnbCerealBlack/AirbnbCerealExtraBold.ttf
    #     - asset: assets/fonts/AirbnbCerealBlack/AirbnbCerealLight.ttf
    #     - asset: assets/fonts/AirbnbCerealBlack/AirbnbCerealMedium.ttf

    # - family: Airbnb
    #   fonts:
    #     - asset: assets/fonts/Airbnb/AirbnbCereal_W_Bd.otf
    #     - asset: assets/fonts/Airbnb/AirbnbCereal_W_Bk.otf
    #     - asset: assets/fonts/Airbnb/AirbnbCereal_W_Blk.otf
    #     - asset: assets/fonts/Airbnb/AirbnbCereal_W_Lt.otf
    #     - asset: assets/fonts/Airbnb/AirbnbCereal_W_Md.otf
    #     - asset: assets/fonts/Airbnb/AirbnbCereal_W_XBd.otf

    - family: SFCompact
      fonts:
        - asset: assets/fonts/SFCompact/SF-Compact.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Display-Black.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Rounded-Semibold.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-Black.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-MediumItalic.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Rounded-Heavy.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-Light.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Display-Heavy.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-Regular.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Rounded-Medium.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Rounded-Regular.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-Ultralight.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-UltralightItalic.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-HeavyItalic.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-Medium.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-RegularItalic.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-BlackItalic.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Display-Regular.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Rounded-Bold.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-Thin.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-LightItalic.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-Heavy.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Display-Medium.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-Semibold.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Rounded-Light.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-Bold.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Display-Semibold.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Rounded-Thin.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Display-Ultralight.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-BoldItalic.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Rounded-Ultralight.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Italic.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Display-Bold.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Display-Light.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Rounded-Black.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-SemiboldItalic.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Text-ThinItalic.ttf
        - asset: assets/fonts/SFCompact/SF-Compact-Display-Thin.ttf

    # - family: SFPro
    #   fonts:
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-LightItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-Bold.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-SemiboldItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-Light.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-MediumItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-Regular.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-UltralightItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-LightItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-BoldItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-Heavy.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-LightItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-Thin.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-Ultralight.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-RegularItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-LightItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-BoldItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-SemiboldItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-BoldItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-HeavyItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-HeavyItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-LightItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-BoldItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-SemiboldItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-LightItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-UltralightItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-RegularItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-MediumItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-MediumItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-RegularItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-BlackItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-HeavyItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-LightItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-ThinItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-BoldItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-SemiboldItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-MediumItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Display-RegularItalic.ttf
    #     - asset: assets/fonts/SFPro/SF-Pro-Text-SemiboldItalic.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
